language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install pip==18.0
  - python setup.py install

script:
  - python -m unittest -v tests
