language: python
os: linux
dist: xenial

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pip==19.0.3 pipenv==2018.11.26
  - pipenv install --dev
  - python setup.py install

script:
  - python -m unittest -v tests
  - coverage run -m unittest -v tests
  - coverage report --include="*/rule_engine/*"

jobs:
  include:
    - stage: Documentation
      if: branch = master
      python: "3.8"
      script:
        - sphinx-build -b html -a -E -v docs/source docs/html
        - echo "Deploying to GitHub pages..."
      deploy:
        local_dir: docs/html
        provider: pages
        cleanup: false
        keep_history: true
        github_token: $GITHUB_TOKEN
