language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pip==19.0.3 pipenv==2018.11.26
  - pipenv install --dev
  - python setup.py install

script:
  - python -m unittest -v tests
