language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install pip==19.0.3 pipenv==2018.11.26
  - pipenv install --dev
  - python setup.py install

script:
  - python -m unittest -v tests

jobs:
  include:
    - stage: Documentation
      python: "3.8"
      script:
        - sphinx-build -b html -a -E -v docs/source docs/html
        - echo "Deploying to GitHub pages..."
      deploy:
        local_dir: docs/html
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GITHUB_TOKEN
